apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-postgres
  labels:
    app.kubernetes.io/component: postgres
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: postgres
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
