{{- if .Values.sandboxWg.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-sandbox-wg" (include "chart.fullname" .)) .Values.worker.worker.env.sandboxWgSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: sandbox-wg
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  private-key: {{ .Values.sandboxWg.privateKey | quote }}
  server-public-key: {{ .Values.sandboxWg.serverPublicKey | quote }}
  server-endpoint: {{ .Values.sandboxWg.serverEndpoint | quote }}
{{- end }}
