#!/usr/bin/env bash
# 2-generate-clients.sh — generate WG keypairs for hub-platform scanners.
#
# Run this on the OPERATOR's machine (where you have helm + kubectl). Outputs:
#   - wg-clients/<peer>.priv       per-peer private key files (chmod 600)
#   - wg-clients/<peer>.pub        per-peer public key files
#   - wg-values.yaml               ready-to-use helm values block (-f wg-values.yaml)
#   - wg-server-peers.txt          [Peer] blocks to APPEND on the WG server
#
# Usage:
#   ./2-generate-clients.sh \
#       --server-pubkey '<paste server.pub>' \
#       --server-endpoint '1.2.3.4:51820' \
#       [--out-dir wg-clients]
#
# After running, copy wg-server-peers.txt to the WG server and run
# scripts/wg/3-register-peers.sh on the server. Finally helm install with
#   helm install hub charts/hub-platform -f wg-values.yaml \
#     --set wireguard.enabled=true \
#     --set domainscope.wireguard.enabled=true \
#     --set openvas.wireguard.enabled=true \
#     --set zap.wireguard.enabled=true

set -euo pipefail

SERVER_PUBKEY=""
SERVER_ENDPOINT=""
OUT_DIR="wg-clients"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --server-pubkey)   SERVER_PUBKEY="$2"; shift 2 ;;
    --server-endpoint) SERVER_ENDPOINT="$2"; shift 2 ;;
    --out-dir)         OUT_DIR="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,/^$/p' "$0"; exit 0 ;;
    *)
      echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$SERVER_PUBKEY" || -z "$SERVER_ENDPOINT" ]]; then
  echo "Both --server-pubkey and --server-endpoint are required." >&2
  echo "Get them from output of scripts/wg/1-setup-server.sh." >&2
  exit 1
fi

if ! command -v wg >/dev/null; then
  echo "Need 'wg' (wireguard-tools) installed locally to generate keys." >&2
  echo "  macOS:  brew install wireguard-tools" >&2
  echo "  Linux:  apt install wireguard-tools / dnf install wireguard-tools" >&2
  exit 1
fi

PEERS=("domainscope:10.200.0.2" "openvas:10.200.0.3" "zap:10.200.0.4")

mkdir -p "$OUT_DIR"
umask 077

cat > wg-values.yaml <<EOF
## Generated by scripts/wg/2-generate-clients.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
## Pass to helm:
##   helm install hub charts/hub-platform -f wg-values.yaml \\
##     --set wireguard.enabled=true \\
##     --set domainscope.wireguard.enabled=true \\
##     --set openvas.wireguard.enabled=true \\
##     --set zap.wireguard.enabled=true
##
## (The per-subchart wireguard.enabled flags toggle the WG sidecar in each pod.)

wireguard:
  enabled: true
  serverPublicKey: ${SERVER_PUBKEY}
  serverEndpoint: ${SERVER_ENDPOINT}
  peers:
EOF

echo "## [Peer] blocks generated by 2-generate-clients.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)" > wg-server-peers.txt
echo "## Append to /etc/wireguard/wg0.conf on the WG server, then run 3-register-peers.sh." >> wg-server-peers.txt
echo >> wg-server-peers.txt

for entry in "${PEERS[@]}"; do
  peer="${entry%%:*}"
  ip="${entry##*:}"

  wg genkey > "${OUT_DIR}/${peer}.priv"
  wg pubkey < "${OUT_DIR}/${peer}.priv" > "${OUT_DIR}/${peer}.pub"

  priv="$(cat "${OUT_DIR}/${peer}.priv")"
  pub="$(cat "${OUT_DIR}/${peer}.pub")"

  cat >> wg-values.yaml <<EOF
    ${peer}:
      privateKey: "${priv}"
      podIp: "${ip}/32"
EOF

  cat >> wg-server-peers.txt <<EOF
[Peer]
# ${peer}
PublicKey = ${pub}
AllowedIPs = ${ip}/32

EOF
done

cat <<EOF

================================================================
Generated:
  ${OUT_DIR}/                  per-peer keypairs (chmod 600)
  wg-values.yaml               helm values for hub-platform
  wg-server-peers.txt          [Peer] blocks for the WG server

Next steps:
  1. Copy wg-server-peers.txt to the WG server, then run there:
       sudo scripts/wg/3-register-peers.sh wg-server-peers.txt
  2. Install or upgrade hub-platform with WG enabled:
       helm install hub charts/hub-platform -f wg-values.yaml \\
         --set wireguard.enabled=true \\
         --set domainscope.wireguard.enabled=true \\
         --set openvas.wireguard.enabled=true \\
         --set zap.wireguard.enabled=true

WARNING: keep ${OUT_DIR}/*.priv files — they are NOT recoverable if lost.
================================================================
EOF
