apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-domainscope-logs
  labels:
    app.kubernetes.io/component: domainscope
    {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- with .Values.storage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.logs.size | quote }}
{{- if .Values.postgres.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-postgres-data
  labels:
    app.kubernetes.io/component: postgres
    {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- with .Values.postgres.storage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size | quote }}
{{- end }}
