{{- if include "chart.shouldCreateSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.secretsName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  secretKey: {{ include "chart.resolveSecret" (dict "ctx" . "key" "secretKey" "length" 50) | quote }}
  superuserPassword: {{ include "chart.resolveSecret" (dict "ctx" . "key" "superuserPassword" "length" 24) | quote }}
  superuserApiToken: {{ include "chart.resolveSecret" (dict "ctx" . "key" "superuserApiToken" "length" 40) | quote }}
  dbPassword: {{ include "chart.resolveSecret" (dict "ctx" . "key" "dbPassword" "length" 32) | quote }}
  redisPassword: {{ include "chart.resolveSecret" (dict "ctx" . "key" "redisPassword" "length" 32) | quote }}
{{- end }}
